#! /bin/sh
echo /dev/sdd first pass.
dd if=/dev/urandom of=/dev/sdd bs=1M status=progress
echo /dev/sdd first pass..
dd if=/dev/urandom of=/dev/sdd bs=1M status=progress
echo /dev/sdd first pass...
dd if=/dev/urandom of=/dev/sdd bs=1M status=progress
echo /dev/sdd first pass....
dd if=/dev/urandom of=/dev/sdd bs=1M status=progress
echo /dev/sdd first pass.....
dd if=/dev/urandom of=/dev/sdd bs=1M status=progress
echo /dev/sdd first pass......
dd if=/dev/urandom of=/dev/sdd bs=1M status=progress
echo /dev/sdd first pass.......
dd if=/dev/urandom of=/dev/sdd bs=1M status=progress
echo completed /dev/sdd first pass!
echo Check for success on written data amount /dev/sdd GB each first pass
echo 
exit


