#! /bin/sh
echo /dev/sdx first pass.
dd if=/dev/urandom of=/dev/sdx bs=1M status=progress
echo /dev/sdx first pass..
dd if=/dev/urandom of=/dev/sdx bs=1M status=progress
echo /dev/sdx first pass...
dd if=/dev/urandom of=/dev/sdx bs=1M status=progress
echo /dev/sdx first pass....
dd if=/dev/urandom of=/dev/sdx bs=1M status=progress
echo /dev/sdx first pass.....
dd if=/dev/urandom of=/dev/sdx bs=1M status=progress
echo /dev/sdx first pass......
dd if=/dev/urandom of=/dev/sdx bs=1M status=progress
echo /dev/sdx first pass.......
dd if=/dev/urandom of=/dev/sdx bs=1M status=progress
echo completed /dev/sdx first pass!
echo Check for success on written data amount /dev/sdx GB each first pass
echo 
exit


