#! /bin/sh
date_time=$(date +'%A %d %B %Y %H:%M:%S')
day_year=$(date +'%j')
day_quarter=$(date +'%q')
day_week=$(date +'%u')
week_year=$(date +'%W')
Year=$(date +'%Y')
time=$(date +'%H:%M:%S')
echo $(date +'%A %d %B %Y')
echo Day $day_year of Year $Year quarter $day_quarter 
echo Day $day_week of week $week_year of Year $Year
echo $time /dev/sdx first pass.
dd if=/dev/urandom of=/dev/sdx bs=1M status=progress
time=$(date +'%H:%M:%S')
echo $time /dev/sdx first pass..
dd if=/dev/urandom of=/dev/sdx bs=1M status=progress
time=$(date +'%H:%M:%S')
echo $time /dev/sdx first pass...
dd if=/dev/urandom of=/dev/sdx bs=1M status=progress
time=$(date +'%H:%M:%S')
echo $time /dev/sdx first pass....
dd if=/dev/urandom of=/dev/sdx bs=1M status=progress
time=$(date +'%H:%M:%S')
echo $time /dev/sdx first pass.....
dd if=/dev/urandom of=/dev/sdx bs=1M status=progress
time=$(date +'%H:%M:%S')
echo $time /dev/sdx first pass......
dd if=/dev/urandom of=/dev/sdx bs=1M status=progress
time=$(date +'%H:%M:%S')
echo $time /dev/sdx first pass.......
dd if=/dev/urandom of=/dev/sdx bs=1M status=progress
time=$(date +'%H:%M:%S')
echo $time completed /dev/sdx first pass!
echo Check for success on written data amount /dev/sdx GB each first pass
echo 
exit


