#! /bin/sh
echo /dev/sdk first pass.
dd if=/dev/urandom of=/dev/sdk bs=1M status=progress
echo /dev/sdk first pass..
dd if=/dev/urandom of=/dev/sdk bs=1M status=progress
echo /dev/sdk first pass...
dd if=/dev/urandom of=/dev/sdk bs=1M status=progress
echo /dev/sdk first pass....
dd if=/dev/urandom of=/dev/sdk bs=1M status=progress
echo /dev/sdk first pass.....
dd if=/dev/urandom of=/dev/sdk bs=1M status=progress
echo /dev/sdk first pass......
dd if=/dev/urandom of=/dev/sdk bs=1M status=progress
echo /dev/sdk first pass.......
dd if=/dev/urandom of=/dev/sdk bs=1M status=progress
echo completed /dev/sdk first pass!
echo Check for success on written data amount /dev/sdk GB each first pass
echo 
exit


