#! /bin/sh
echo /dev/sdh first pass.
dd if=/dev/urandom of=/dev/sdh bs=1M status=progress
echo /dev/sdh first pass..
dd if=/dev/urandom of=/dev/sdh bs=1M status=progress
echo /dev/sdh first pass...
dd if=/dev/urandom of=/dev/sdh bs=1M status=progress
echo /dev/sdh first pass....
dd if=/dev/urandom of=/dev/sdh bs=1M status=progress
echo /dev/sdh first pass.....
dd if=/dev/urandom of=/dev/sdh bs=1M status=progress
echo /dev/sdh first pass......
dd if=/dev/urandom of=/dev/sdh bs=1M status=progress
echo /dev/sdh first pass.......
dd if=/dev/urandom of=/dev/sdh bs=1M status=progress
echo completed /dev/sdh first pass!
echo Check for success on written data amount /dev/sdh GB each first pass
echo 
exit


