#! /bin/sh
echo /dev/sdr first pass.
dd if=/dev/urandom of=/dev/sdr bs=1M status=progress
echo /dev/sdr first pass..
dd if=/dev/urandom of=/dev/sdr bs=1M status=progress
echo /dev/sdr first pass...
dd if=/dev/urandom of=/dev/sdr bs=1M status=progress
echo /dev/sdr first pass....
dd if=/dev/urandom of=/dev/sdr bs=1M status=progress
echo /dev/sdr first pass.....
dd if=/dev/urandom of=/dev/sdr bs=1M status=progress
echo /dev/sdr first pass......
dd if=/dev/urandom of=/dev/sdr bs=1M status=progress
echo /dev/sdr first pass.......
dd if=/dev/urandom of=/dev/sdr bs=1M status=progress
echo completed /dev/sdr first pass!
echo Check for success on written data amount /dev/sdr GB each first pass
echo 
exit


