#! /bin/sh
echo /dev/sdo first pass.
dd if=/dev/urandom of=/dev/sdo bs=1M status=progress
echo /dev/sdo first pass..
dd if=/dev/urandom of=/dev/sdo bs=1M status=progress
echo /dev/sdo first pass...
dd if=/dev/urandom of=/dev/sdo bs=1M status=progress
echo /dev/sdo first pass....
dd if=/dev/urandom of=/dev/sdo bs=1M status=progress
echo /dev/sdo first pass.....
dd if=/dev/urandom of=/dev/sdo bs=1M status=progress
echo /dev/sdo first pass......
dd if=/dev/urandom of=/dev/sdo bs=1M status=progress
echo /dev/sdo first pass.......
dd if=/dev/urandom of=/dev/sdo bs=1M status=progress
echo completed /dev/sdo first pass!
echo Check for success on written data amount /dev/sdo GB each first pass
echo 
exit


