#! /bin/sh
echo /dev/sdf first pass.
dd if=/dev/urandom of=/dev/sdf bs=1M status=progress
echo /dev/sdf first pass..
dd if=/dev/urandom of=/dev/sdf bs=1M status=progress
echo /dev/sdf first pass...
dd if=/dev/urandom of=/dev/sdf bs=1M status=progress
echo /dev/sdf first pass....
dd if=/dev/urandom of=/dev/sdf bs=1M status=progress
echo /dev/sdf first pass.....
dd if=/dev/urandom of=/dev/sdf bs=1M status=progress
echo /dev/sdf first pass......
dd if=/dev/urandom of=/dev/sdf bs=1M status=progress
echo /dev/sdf first pass.......
dd if=/dev/urandom of=/dev/sdf bs=1M status=progress
echo completed /dev/sdf first pass!
echo Check for success on written data amount /dev/sdf GB each first pass
echo 
exit


