#! /bin/sh
echo first pass. && \
dd if=/dev/urandom of=/dev/sde bs=1M status=progress && \
echo first pass.. && \
dd if=/dev/urandom of=/dev/sde bs=1M status=progress && \
echo first pass... && \
dd if=/dev/urandom of=/dev/sde bs=1M status=progress && \
echo first pass.... && \
dd if=/dev/urandom of=/dev/sde bs=1M status=progress && \
echo first pass..... && \
dd if=/dev/urandom of=/dev/sde bs=1M status=progress && \
echo first pass...... && \
dd if=/dev/urandom of=/dev/sde bs=1M status=progress && \
echo first pass....... && \
dd if=/dev/urandom of=/dev/sde bs=1M status=progress && \
echo completed first pass!
exit


