#! /bin/sh
echo /dev/sdu first pass.
dd if=/dev/urandom of=/dev/sdu bs=1M status=progress
echo /dev/sdu first pass..
dd if=/dev/urandom of=/dev/sdu bs=1M status=progress
echo /dev/sdu first pass...
dd if=/dev/urandom of=/dev/sdu bs=1M status=progress
echo /dev/sdu first pass....
dd if=/dev/urandom of=/dev/sdu bs=1M status=progress
echo /dev/sdu first pass.....
dd if=/dev/urandom of=/dev/sdu bs=1M status=progress
echo /dev/sdu first pass......
dd if=/dev/urandom of=/dev/sdu bs=1M status=progress
echo /dev/sdu first pass.......
dd if=/dev/urandom of=/dev/sdu bs=1M status=progress
echo completed /dev/sdu first pass!
echo Check for success on written data amount /dev/sdu GB each first pass
echo 
exit


