#! /bin/sh
date_time=$(date +'%A %d %B %Y %H:%M:%S')
day_year=$(date +'%j')
day_quarter=$(date +'%q')
day_week=$(date +'%u')
week_year=$(date +'%W')
Year=$(date +'%Y')
time=$(date +'%H:%M:%S')
echo $(date +'%A %d %B %Y')
echo Day $day_year of Year $Year quarter $day_quarter 
echo Day $day_week of week $week_year of Year $Year
echo $time /dev/sds first pass.
dd if=/dev/urandom of=/dev/sds bs=1M status=progress
time=$(date +'%H:%M:%S')
echo $time /dev/sds first pass..
dd if=/dev/urandom of=/dev/sds bs=1M status=progress
time=$(date +'%H:%M:%S')
echo $time /dev/sds first pass...
dd if=/dev/urandom of=/dev/sds bs=1M status=progress
time=$(date +'%H:%M:%S')
echo $time /dev/sds first pass....
dd if=/dev/urandom of=/dev/sds bs=1M status=progress
time=$(date +'%H:%M:%S')
echo $time /dev/sds first pass.....
dd if=/dev/urandom of=/dev/sds bs=1M status=progress
time=$(date +'%H:%M:%S')
echo $time /dev/sds first pass......
dd if=/dev/urandom of=/dev/sds bs=1M status=progress
time=$(date +'%H:%M:%S')
echo $time /dev/sds first pass.......
dd if=/dev/urandom of=/dev/sds bs=1M status=progress
time=$(date +'%H:%M:%S')
echo $time completed /dev/sds first pass!
echo Check for success on written data amount /dev/sds GB each first pass
echo 
exit


