#! /bin/sh
echo /dev/sde first pass.
dd if=/dev/urandom of=/dev/sde bs=1M status=progress
echo /dev/sde first pass..
dd if=/dev/urandom of=/dev/sde bs=1M status=progress
echo /dev/sde first pass...
dd if=/dev/urandom of=/dev/sde bs=1M status=progress
echo /dev/sde first pass....
dd if=/dev/urandom of=/dev/sde bs=1M status=progress
echo /dev/sde first pass.....
dd if=/dev/urandom of=/dev/sde bs=1M status=progress
echo /dev/sde first pass......
dd if=/dev/urandom of=/dev/sde bs=1M status=progress
echo /dev/sde first pass.......
dd if=/dev/urandom of=/dev/sde bs=1M status=progress
echo completed /dev/sde first pass!
echo Check for success on written data amount /dev/sde GB each first pass
echo 
exit


