#! /bin/sh
echo /dev/sdc first pass.
dd if=/dev/urandom of=/dev/sdc bs=1M status=progress
echo /dev/sdc first pass..
dd if=/dev/urandom of=/dev/sdc bs=1M status=progress
echo /dev/sdc first pass...
dd if=/dev/urandom of=/dev/sdc bs=1M status=progress
echo /dev/sdc first pass....
dd if=/dev/urandom of=/dev/sdc bs=1M status=progress
echo /dev/sdc first pass.....
dd if=/dev/urandom of=/dev/sdc bs=1M status=progress
echo /dev/sdc first pass......
dd if=/dev/urandom of=/dev/sdc bs=1M status=progress
echo /dev/sdc first pass.......
dd if=/dev/urandom of=/dev/sdc bs=1M status=progress
echo completed /dev/sdc first pass!
echo Check for success on written data amount /dev/sdc GB each first pass
echo 
exit


