#! /bin/sh
echo /dev/sdj first pass.
dd if=/dev/urandom of=/dev/sdj bs=1M status=progress
echo /dev/sdj first pass..
dd if=/dev/urandom of=/dev/sdj bs=1M status=progress
echo /dev/sdj first pass...
dd if=/dev/urandom of=/dev/sdj bs=1M status=progress
echo /dev/sdj first pass....
dd if=/dev/urandom of=/dev/sdj bs=1M status=progress
echo /dev/sdj first pass.....
dd if=/dev/urandom of=/dev/sdj bs=1M status=progress
echo /dev/sdj first pass......
dd if=/dev/urandom of=/dev/sdj bs=1M status=progress
echo /dev/sdj first pass.......
dd if=/dev/urandom of=/dev/sdj bs=1M status=progress
echo completed /dev/sdj first pass!
echo Check for success on written data amount /dev/sdj GB each first pass
echo 
exit


