#! /bin/sh
echo /dev/sdb first pass.
dd if=/dev/urandom of=/dev/sdb bs=1M status=progress
echo /dev/sdb first pass..
dd if=/dev/urandom of=/dev/sdb bs=1M status=progress
echo /dev/sdb first pass...
dd if=/dev/urandom of=/dev/sdb bs=1M status=progress
echo /dev/sdb first pass....
dd if=/dev/urandom of=/dev/sdb bs=1M status=progress
echo /dev/sdb first pass.....
dd if=/dev/urandom of=/dev/sdb bs=1M status=progress
echo /dev/sdb first pass......
dd if=/dev/urandom of=/dev/sdb bs=1M status=progress
echo /dev/sdb first pass.......
dd if=/dev/urandom of=/dev/sdb bs=1M status=progress
echo completed /dev/sdb first pass!
echo Check for success on written data amount /dev/sdb GB each first pass
echo 
exit


