#! /bin/sh
echo /dev/sdi first pass.
dd if=/dev/urandom of=/dev/sdi bs=1M status=progress
echo /dev/sdi first pass..
dd if=/dev/urandom of=/dev/sdi bs=1M status=progress
echo /dev/sdi first pass...
dd if=/dev/urandom of=/dev/sdi bs=1M status=progress
echo /dev/sdi first pass....
dd if=/dev/urandom of=/dev/sdi bs=1M status=progress
echo /dev/sdi first pass.....
dd if=/dev/urandom of=/dev/sdi bs=1M status=progress
echo /dev/sdi first pass......
dd if=/dev/urandom of=/dev/sdi bs=1M status=progress
echo /dev/sdi first pass.......
dd if=/dev/urandom of=/dev/sdi bs=1M status=progress
echo completed /dev/sdi first pass!
echo Check for success on written data amount /dev/sdi GB each first pass
echo 
exit


