#! /bin/sh
echo /dev/sdg first pass.
dd if=/dev/urandom of=/dev/sdg bs=1M status=progress
echo /dev/sdg first pass..
dd if=/dev/urandom of=/dev/sdg bs=1M status=progress
echo /dev/sdg first pass...
dd if=/dev/urandom of=/dev/sdg bs=1M status=progress
echo /dev/sdg first pass....
dd if=/dev/urandom of=/dev/sdg bs=1M status=progress
echo /dev/sdg first pass.....
dd if=/dev/urandom of=/dev/sdg bs=1M status=progress
echo /dev/sdg first pass......
dd if=/dev/urandom of=/dev/sdg bs=1M status=progress
echo /dev/sdg first pass.......
dd if=/dev/urandom of=/dev/sdg bs=1M status=progress
echo completed /dev/sdg first pass!
echo Check for success on written data amount /dev/sdg GB each first pass
echo 
exit


